version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          TEST_DATABASE_URL: postgresql://blockchain_test@localhost:5432/blockchain_test

      - image: circleci/postgres:10.5-ram
        environment:
          POSTGRES_USER: blockchain_test
          POSTGRES_DB: blockchain_test
          POSTGRES_PASSWORD: password

      - image: trufflesuite/ganache-cli:latest
        command: [
          "--account=0x4843d7e2658482c2cab8cf79576e4112d156fd87dda1e08468b51fe34fd08569, 100000000000000000000",
          "--account=0xc0c85e6b373d090048676f0c82542cb3bb6793491450f478b147614262718cdd, 100000000000000000000",
          "--account=0xe8c7e2bdd82569189d73cb618391973c8f52d8ba651446a00a87cc67c8219781, 100000000000000000000",
          "--account=0x215d6c308a70b5b74081ec71f7d67495b0c3c88bf0ba119b8eeb022cf2c20251, 100000000000000000000",
          "--account=0xe57787b6142f659d759fcbe2ecda7e49f105fd61b10f73d980ab1964aef71132, 100000000000000000000"
        ]

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run all tests
          command: gradle test
      - run:
          name: Kotlin linter
          command: gradle ktlint

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          TEST_DATABASE_URL: postgresql://blockchain_test@localhost:5432/blockchain_test

      - image: circleci/postgres:10.5-ram
        environment:
          POSTGRES_USER: blockchain_test
          POSTGRES_DB: blockchain_test
          POSTGRES_PASSWORD: password

      - image: trufflesuite/ganache-cli:latest
        command: [
          "--account=0x4843d7e2658482c2cab8cf79576e4112d156fd87dda1e08468b51fe34fd08569, 100000000000000000000",
          "--account=0xc0c85e6b373d090048676f0c82542cb3bb6793491450f478b147614262718cdd, 100000000000000000000",
          "--account=0xe8c7e2bdd82569189d73cb618391973c8f52d8ba651446a00a87cc67c8219781, 100000000000000000000",
          "--account=0x215d6c308a70b5b74081ec71f7d67495b0c3c88bf0ba119b8eeb022cf2c20251, 100000000000000000000"
        ]

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build
          command: gradle build

      - run:
          name: Push image to Docker Hub
          command: gradle jib

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
